<?php
    define('PBCMS_DEBUG_MODE', VAL_PBCMS_DEBUG_MODE);

    define('DATABASE_HOSTNAME', 'VAL_DATABASE_HOSTNAME');
    define('DATABASE_USERNAME', 'VAL_DATABASE_USERNAME');
    define('DATABASE_PASSWORD', 'VAL_DATABASE_PASSWORD');
    define('DATABASE_DATABASE', 'VAL_DATABASE_DATABASE');
    define('DATABASE_TABLE_PREFIX', 'VAL_DATABASE_TABLE_PREFIX');
